# Generated by Django 5.2.1 on 2025-05-22 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален?')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='ссылка на изображение')),
                ('category', models.CharField(choices=[('books', 'Книги'), ('clothes', 'Одежда'), ('shoes', 'Обувь'), ('electronics', 'Электроника'), ('toys', 'Игрушки'), ('furniture', 'Мебель'), ('sports', 'Спорттовары'), ('kitchen', 'Кухонная утварь'), ('accessories', 'Аксессуары'), ('tools', 'Инструменты'), ('other', 'Другое')], max_length=50, verbose_name='категория')),
                ('condition', models.CharField(choices=[('new', 'Новый'), ('used', 'Б/У')], max_length=10, verbose_name='состояние')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='DeletedAd',
            fields=[
            ],
            options={
                'verbose_name': 'Объявление удаленное',
                'verbose_name_plural': 'Объявления удаленные',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ads.ad',),
        ),
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален?')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принят'), ('declined', 'Отклонен')], default='pending', max_length=10, verbose_name='статус')),
                ('ad_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_proposals', to='ads.ad', verbose_name='предложение получателя')),
                ('ad_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to='ads.ad', verbose_name='предложение отправителя')),
            ],
            options={
                'verbose_name': 'Предложение обмена',
                'verbose_name_plural': 'Предложения обмена',
            },
        ),
    ]
