# Generated by Django 5.2.1 on 2025-05-24 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_title_alter_exchangeproposal_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['created_at', 'updated_at'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='exchangeproposal',
            options={'ordering': ['created_at', 'updated_at'], 'verbose_name': 'Предложение обмена', 'verbose_name_plural': 'Предложения обмена'},
        ),
    ]
