# Generated by Django 5.2.1 on 2025-05-27 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_ad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeproposal',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name': 'Предложение обмена', 'verbose_name_plural': 'Предложения обмена'},
        ),
        migrations.RemoveField(
            model_name='exchangeproposal',
            name='comment',
        ),
        migrations.AddField(
            model_name='exchangeproposal',
            name='comment_receiver',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='комментарий получателя'),
        ),
        migrations.AddField(
            model_name='exchangeproposal',
            name='comment_sender',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='комментарий отправителя'),
        ),
    ]
